=== jebeck/everest-data/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "https://github.com/jebeck/everest-data",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Name": {
        "type": "string"
      },
      "Date": {
        "type": "string",
        "pattern": "\\d\\d\\d\\d-\\d\\d(-\\d\\d)?"
      },
      "Age": {
        "type": [
          "number",
          "null"
        ]
      },
      "Expedition": {
        "type": [
          "string",
          "null"
        ]
      },
      "Nationality": {
        "type": "string"
      },
      "Cause of death": {
        "type": [
          "string",
          "null"
        ]
      },
      "General location": {
        "type": [
          "string",
          "null"
        ]
      },
      "Specific location": {
        "type": "string"
      },
      "Elevation": {
        "type": "integer",
        "minimum": 0,
        "maximum": 8848
      },
      "Cause of death details": {
        "type": "string"
      }
    },
    "required": [
      "Name",
      "Date",
      "Age",
      "Expedition",
      "Nationality",
      "Cause of death",
      "General location"
    ],
    "additionalProperties": false
  }
}

=== jebeck/everest-data/died-climbing-Everest.json
[
 {
   "Name": "Dorje",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Lhakpa",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Norbu",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Pasang",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Pema",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Sange",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Temba",
   "Date": "1922-06-07",
   "Age": null,
   "Expedition": "1922 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "North Col",
   "Specific location": "Below North Col"
 },
 {
   "Name": "Man Bahadur",
   "Date": "1924-05-13",
   "Age": null,
   "Expedition": "1924 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Pneumonia",
   "General location": "Rongbuk B.C.",
   "Specific location": "Above Rongbuk B.C."
 },
 {
   "Name": "Lance-Naik Shamsherpun",
   "Date": "1924-05-17",
   "Age": null,
   "Expedition": "1924 British Mount Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Brain hemorrhage",
   "General location": "Rongbuk B.C.",
   "Specific location": "Above Rongbuk B.C."
 },
 {
   "Name": "Andrew Irvine",
   "Date": "1924-06-09",
   "Age": 22,
   "Expedition": "1924 British Mount Everest Expedition",
   "Nationality": "United Kingdom",
   "Cause of death": "Disappeared; body never found; cause of death unknown",
   "General location": "N.E. Ridge"
 },
 {
   "Name": "George Mallory",
   "Date": "1924-06-09",
   "Age": 37,
   "Expedition": "1924 British Mount Everest Expedition",
   "Nationality": "United Kingdom",
   "Cause of death": "Disappeared; body found in 1999; evidence suggests Mallory died from being accidentally struck by his ice axe following a fall.",
   "General location": "N.E. Ridge"
 },
 {
   "Name": "Maurice Wilson",
   "Date": "1934-05-31",
   "Age": 36,
   "Expedition": "Solo Expedition",
   "Nationality": "United Kingdom",
   "Cause of death": "Body found 1935; cause of death possibly exhaustion, exposure or starvation.",
   "General location": "East Rongbuk glacier"
 },
 {
   "Name": "Dorje Mingma",
   "Date": "1952-10-31",
   "Age": null,
   "Expedition": "Swiss Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Falling ice",
   "General location": "Lhotse Face"
 },
 {
   "Name": "Wang Ji",
   "Date": "1960-04-11",
   "Age": null,
   "Expedition": "Chinese Expedition Northern Slope",
   "Nationality": "China",
   "Cause of death": "Mountain sickness",
   "General location": null
 },
 {
   "Name": "Shao Shi-Ching",
   "Date": "1960-04-29",
   "Age": null,
   "Expedition": "Chinese Expedition Northern Slope",
   "Nationality": "China",
   "Cause of death": null,
   "General location": "N.E. Ridge"
 },
 {
   "Name": "Nawang Tshering",
   "Date": "1962-04-28",
   "Age": null,
   "Expedition": "Chinese Expedition Northern Slope",
   "Nationality": "Nepal",
   "Cause of death": null,
   "General location": "Lhotse face"
 },
 {
   "Name": "Jake Breitenbach",
   "Date": "1963-03-23",
   "Age": 27,
   "Expedition": "Norman Dyhrenfurth's American Mount Everest Expedition",
   "Nationality": "United States",
   "Cause of death": "Crushed under serac",
   "General location": "Icefall"
 },
 {
   "Name": "Ma Gao-shu",
   "Date": "1966-05-01",
   "Age": null,
   "Expedition": "Chinese Everest Expedition",
   "Nationality": "China",
   "Cause of death": "Fall",
   "General location": "Icefall"
 },
 {
   "Name": "Phu Dorje",
   "Date": "1969-10-18",
   "Age": null,
   "Expedition": "Japanese Everest Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Fall into a crevice",
   "General location": "Icefall"
 },
 {
   "Name": "Nima Dorje",
   "Date": "1970-04-05",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "Icefall"
 },
 {
   "Name": "Kunga Norbu",
   "Date": "1970-04-05",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null
 },
 {
   "Name": "Mima Norbu",
   "Date": "1970-04-05",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "Icefall"
 },
 {
   "Name": "Pasang",
   "Date": "1970-04-05",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "Icefall"
 },
 {
   "Name": "Kami Tshering",
   "Date": "1970-04-05",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "Icefall"
 },
 {
   "Name": "Kyak Tshering",
   "Date": "1970-04-05",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "Icefall"
 },
 {
   "Name": "Kyak Tshering",
   "Date": "1970-04-09",
   "Age": 36,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 5525
 },
 {
   "Name": "Kiyoshi Narita",
   "Date": "1970-04-21",
   "Age": null,
   "Expedition": "Japanese Skiing Expedition",
   "Nationality": "Japan",
   "Cause of death": "Heart attack",
   "General location": null,
   "Elevation": 6150
 },
 {
   "Name": "Harsh Vardhan",
   "Date": "1971-04-18",
   "Age": null,
   "Expedition": "International Expedition of 1971",
   "Nationality": "India",
   "Cause of death": "Succumbed after falling and being suspended above a crevice during a blizzard",
   "General location": null,
   "Elevation": 6900
 },
 {
   "Name": "Tony Tighe",
   "Date": "1972-11-16",
   "Age": null,
   "Expedition": "Mt. Qomolangma expedition",
   "Nationality": "Australia",
   "Cause of death": "Crushed under serac",
   "General location": "Icefall"
 },
 {
   "Name": "Jangbu",
   "Date": "1973-10-12",
   "Age": null,
   "Expedition": null,
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": "S.W. Face"
 },
 {
   "Name": "GÃ©rard Devouassoux",
   "Date": "1974-09-09",
   "Age": null,
   "Expedition": "French West Ridge Direct expedition",
   "Nationality": "France",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 6400
 },
 {
   "Name": "Pemba Dorje",
   "Date": "1974-09-09",
   "Age": null,
   "Expedition": "French West Ridge Direct expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 6400
 },
 {
   "Name": "Lhakpa",
   "Date": "1974-09-09",
   "Age": null,
   "Expedition": "French West Ridge Direct expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 6400
 },
 {
   "Name": "Nawang Lutuk",
   "Date": "1974-09-09",
   "Age": null,
   "Expedition": "French West Ridge Direct expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 6400
 },
 {
   "Name": "Nima Wangchu",
   "Date": "1974-09-09",
   "Age": null,
   "Expedition": "French West Ridge Direct expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 6400
 },
 {
   "Name": "Sanu Wongal",
   "Date": "1974-09-09",
   "Age": null,
   "Expedition": "French West Ridge Direct expedition",
   "Nationality": "Nepal",
   "Cause of death": "Avalanche",
   "General location": null,
   "Elevation": 6400
 },
 {
   "Name": "Wu Zhuong Yue",
   "Date": "1975-05-04",
   "Age": null,
   "Expedition": null,
   "Nationality": "China",
   "Cause of death": "Exhaustion, fall",
   "General location": null,
   "Elevation": 8500
 },
 {
   "Name": "Mick Burke",
   "Date": "1975-09-26",
   "Age": 34,
   "Expedition": "Bonington's 1975 Everest expedition",
   "Nationality": "United Kingdom",
   "Cause of death": "Disappearance (likely accidental death during climb)",
   "General location": "Near Summit"
 },
 {
   "Name": "Terry Thompson",
   "Date": "1976-04-10",
   "Age": null,
   "Expedition": "British-Nepal Army Everest Expedition",
   "Nationality": "United Kingdom",
   "Cause of death": "Fall into a crevasse",
   "General location": "Camp 2"
 },
 {
